### PR TITLE
Added a new command line "--all_regions".

### PR DESCRIPTION
**Pull request by eduardo-dedalus**
It enables listing the RDS in all regions and permits to get an RDS instance from any region without prior knowing in which region it is.

As I manage hundreds of AWS customers, this made my work easier.

### CODE REVIEW

**Comment by waja** [comment]
Please open a PR at upstream project at https://github.com/percona/percona-monitoring-plugins/pulls! When it's integrated there, we will include it into our packaging when integrating the next upstream release.

**Comment by waja** [comment]
@bzed I think this can be closed, there is a PR at https://github.com/percona/percona-monitoring-plugins/pull/7 too.

**Comment by waja** [comment]
@eduardo-dedalus still, thanks for sharing your code! :-)

**Comment by waja** [comment]
@eduardo-dedalus looking into https://github.com/percona/percona-monitoring-plugins/commit/cee8d4067354c3fec2e9bcd1d83f3f9e2e66331e it indicates, this was implemented into version 1.1.5. I think with the next debian release we will ship this version.

**Comment by eduardo-dedalus** [comment]
@waja my PR in https://github.com/percona/percona-monitoring-plugins/pull/7 uses https://github.com/percona/percona-monitoring-plugins/commit/cee8d4067354c3fec2e9bcd1d83f3f9e2e66331e as the base.

The difference, for our business, is that we need to search the RDS in all regions (no to specify one region only).

I think we can close this one, and I will follow the PR in percona's.

**Pull request closed without merging**
